# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161221_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(null=True, upload_to='profile_image'),
        ),
    ]
